version: "3.9"

services:
  featureflags-client: &base
    image: featureflags-client
    init: true
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: UTF-8
      PYTHONUNBUFFERED: 1
    networks:
      - main
    volumes:
      - ./featureflags_client:/app/featureflags_client
      - ./examples:/app/examples
      - ./.ptpython:/app/.ptpython
      # Uncomment to mount local build of `featureflags_protobuf`
      - ./featureflags_protobuf:/app/featureflags_protobuf

  ishell:
    <<: *base
    image: featureflags-client-examples
    command: pdm run ishell

  test:
    <<: *base
    image: featureflags-client-test
    command: pdm run test ${ARGS}

  docs:
    <<: *base
    image: featureflags-client-docs
    command: sphinx-build -a -b html docs public

networks:
  main:
    driver: bridge
