name: Build & publish

# TODO: Setup release workflow
on:
  push:
    branches: [ "**" ]
    tags:
    - "v*"
#  pull_request:
#    branches: [main]

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/client-')
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upload package to pypi.org
      run: pdm publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
