name: Test

# TODO: enable after test fixes
on: workflow_dispatch
#  pull_request:
#    branches:
#      - main
#    types:
#      - assigned
#      - opened
#      - synchronize
#      - reopened

jobs:
  test-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11, 3.12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox tox-gh-actions tox-pdm
      - name: Test with tox
        run: |
          tox --version
          tox
